### ISSUE TITLE
Stub out Express Server

### ISSUE THREAD

**Issue by chadlatham** [mattstuhring/concert_clue#1]

**Comment by chadlatham** [comment]
Minimum NPM modules:
express --save
nodemon --save-dev
foreman --save-dev
request-promise --save
bcrypt-as-promised --save
knex --save
pg --save
morgan --save
body-parser --save
cookie-session --save
dotenv --save
express-validation --save
joi --save

.gitignore should include at least:
.DS_Store
.env
node_modules
npm-debug.log
pg

**Comment by setfloat** [comment]
Server running on nodemon. Group programmed
